name: A-mem
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - liblzma=5.8.2=hfd05255_0
  - libsqlite=3.51.2=hf5d6505_0
  - libzlib=1.3.1=h2466b09_2
  - openssl=3.6.1=hf411b9b_1
  - packaging=26.0=pyhcf101f3_0
  - pip=26.0.1=pyh8b19718_0
  - python=3.11.14=h0159041_3_cpython
  - setuptools=81.0.0=pyh332efcf_0
  - tk=8.6.13=h6ed50ae_3
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - wheel=0.46.3=pyhd8ed1ab_0
  - pip:
      - absl-py==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - bert-score==0.3.13
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - distro==1.9.0
      - fastuuid==0.14.0
      - filelock==3.20.0
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - idna==3.11
      - importlib-metadata==8.7.1
      - jinja2==3.1.6
      - jiter==0.13.0
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - litellm==1.81.9
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - multidict==6.7.1
      - networkx==3.6.1
      - nltk==3.9.2
      - numpy==1.26.4
      - ollama==0.6.1
      - openai==2.17.0
      - pandas==3.0.0
      - pillow==12.0.0
      - propcache==0.4.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - rank-bm25==0.2.2
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - rouge-score==0.1.2
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - sentence-transformers==5.2.2
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.2
      - torch==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - tqdm==4.67.3
      - transformers==5.1.0
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - yarl==1.22.0
      - zipp==3.23.0
prefix: D:\anacoda\Anaconda envs\envs\A-mem
